I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script call
    call setup
  File "game/script.rpy", line 6, in script call
    call setup
ScriptError: could not find label 'setup'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script call
    call setup
  File "C:\Program Files\renpy-8.2.1-sdk\renpy\ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 6, in script call
    call setup
  File "C:\Program Files\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'setup'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
starter 1.0
Wed Apr 24 14:12:34 2024
